# 배포용
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEPLOY_DB_URL}
    username: ${DEPLOY_DB_USERNAME}
    password: ${DEPLOY_DB_PASSWORD}

  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 1000

kakao:
  client: ${KAKAO_REST_API_KEY}
  redirect: ${KAKAO_REDIRECT_URL}

jwt:
  secret: ${JWT_SECRET}