# 로컬 개발용
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: update # create, update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000

# 2. Thymeleaf(또는 뷰 리졸버)용 설정
  mvc:
    view:
      prefix: /templates/   # Thymeleaf 뷰 파일 위치 (classpath:/templates/)
      suffix: .html         # 뷰 파일 확장자
  data:
    elasticsearch:
      client:
        endpoints: localhost:9200
      repositories:
        enabled: true
# --------------------------------------------------
# 3. 카카오 OAuth 설정
# --------------------------------------------------
kakao:
  client: ${KAKAO_REST_API_KEY}       # 필수: 카카오 개발자 콘솔에서 발급받은 REST API 키
  redirect: http://localhost:5173/landing

#  redirect: ${KAKAO_REDIRECT_URL}
app:
  front:
    redirect-url: http://localhost:5173/landing
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000

naver:
  search:
    client-id: ${NAVER_SEARCH_CLIENT_ID}
    client-secret: ${NAVER_SEARCH_CLIENT_SECRET}
